// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsPipeline.Domain.Context;

namespace NewsPipeline.Domain.Migrations
{
    [DbContext(typeof(NewsFeedDetailsContext))]
    [Migration("20190903092200_v2")]
    partial class v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NewsPipeline.Domain.Entities.NewsFeedDetail", b =>
                {
                    b.Property<int>("NewsID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("Comment");

                    b.Property<string>("Content");

                    b.Property<string>("Description");

                    b.Property<bool>("Like");

                    b.Property<string>("Title");

                    b.HasKey("NewsID");

                    b.ToTable("NewsFeedDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
